# fly.toml app configuration file generated for phone-book2023 on 2023-10-03T11:55:00-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "phone-book2023"
primary_region = "yul"

[build]
  PORT="3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
